mysite/guestbook/urls.py
from django.conf.urls import patterns, url
from guestbook import views

urlpatterns = patterns('',
    url(r'^$', views.index, {'signed_val': False}, name='index'),
    url(r'^/signed/$', views.index, {'signed_val': True}, name='signed_guestbook'),
    url(r'^/view/$', views.view, name='view'),
    url(r'^/sign/$', views.sign, name='sign'),
)

mysite/mysite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    #url(r'^', include('guestbookform.urls')),
    url(r'^', include('guestbook.urls', namespace="guestbook")),
    url(r'^admin/', include(admin.site.urls)),
)

mysite/guestbook/models.py
from django.db import models

# Create your models here.
class Signature(models.Model):
	first_name = models.CharField(max_length=192)
	last_name = models.CharField(max_length=192)
	sign_date = models.DateTimeField('date signed')
	ip = models.CharField(max_length=16)

	def __str__(self):
		return self.first_name+" "+self.last_name

mysite/guestbook/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.utils import timezone
from django.core.urlresolvers import reverse

from guestbook.models import Signature

# Create your views here.
def index(request, signed_val):
    context = {'signed_val': signed_val}
    return render(request, 'guestbook/index.html', context)

def sign(request):
    s = Signature(first_name=request.POST['firstname'], last_name=request.POST['lastname'], sign_date=timezone.now(), ip=request.META.get('REMOTE_ADDR'))
    s.save()
    return HttpResponseRedirect(reverse('guestbook:signed_guestbook', kwargs={'signed_val': True}))

def view(request):
    sig_list = Signature.objects.order_by('-sign_date')[0:]
    context = {'sig_list': sig_list}
    #output = ', '.join([p.first_name+" "+p.last_name for p in sig_list])
    return render(request, 'guestbook/gb_view.html', context)

mysite/guestbook/templates/guestbook/gb_view.html
<!DOCTYPE>
<html>
<head>
    <title>Jason Reed's Guestbook</title>
</head>
<body bgcolor="grey">
<a href="{% url "guestbook:index" %}">Home</a><br>
<h2 style="text-align: center">Guestbook</h2>

{% if sig_list %}
    <ul>Entries<hr />
    {% for signature in sig_list %}
        <li>{{ signature.first_name }} {{ signature.last_name }}</li>
        <p> - signed: {{ signature.sign_date }} - from IP Address: {{ signature.ip }}</p>
    {% endfor %}
{% else %}
    <p>No signatures yet in the guestbook.</p>
{% endif %}

</body>
</html>

mysite/guestbook/templates/guestbook/index.html
<!DOCTYPE html>
<html>
<head>
	<title>Jason Reed Homepage</title>
</head>
<body bgcolor="grey">
    {% load staticfiles %}
    <img src="{% static "guestbook/profile.jpg" %}" alt="Jason Reed" style="display: block;margin-left: auto;margin-right: auto" />
    <br />
    <p style="text-align: center">Jason Reed<br>
    205 E. 12th Street,<br>
    Rolla, MO 65401<br>
    573-202-0890 (C)</p>
    <br />
    <h2>Sign My Guestbook</h2>
    <form method="POST" action="{% url 'guestbook:sign' %}">
        {% csrf_token %}   
        First Name: <input type="text" name="firstname"><br /><br />
        Last Name: <input type="text" name="lastname"><br />
        <input type="submit" value="Sign" />
    </form>
{% if signed_val %}
    <a href="{% url 'guestbook:view' %}">View the Guestbook</a>
{% endif %}
</body>
</html>